/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Qui suis-je ? */
    get: operations["me_api_v1_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Se connecter (e-mail + mot de passe → jeton d'accès)
     * @description Flux OAuth2 « password » : le champ `username` contient l'adresse e-mail.
     */
    post: operations["login_api_v1_auth_token_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/interns": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lister les stagiaires (paginé) */
    get: operations["list_interns_api_v1_interns_get"];
    put?: never;
    /** Inscrire un stagiaire */
    post: operations["register_intern_api_v1_interns_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/interns/{intern_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulter un stagiaire */
    get: operations["get_intern_api_v1_interns__intern_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/internships": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lister les stages (filtres combinables, paginé) */
    get: operations["list_internships_api_v1_internships_get"];
    put?: never;
    /** Planifier un stage */
    post: operations["plan_internship_api_v1_internships_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/internships/{internship_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulter un stage */
    get: operations["get_internship_api_v1_internships__internship_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/internships/{internship_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Annuler un stage prévu ou en cours */
    post: operations["cancel_internship_api_v1_internships__internship_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/internships/{internship_id}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Terminer un stage en cours */
    post: operations["complete_internship_api_v1_internships__internship_id__complete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/internships/{internship_id}/reports": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lister les rapports d'un stage (semaine la plus récente d'abord) */
    get: operations["list_reports_api_v1_internships__internship_id__reports_get"];
    put?: never;
    /** Déposer le rapport de la semaine (stagiaire) */
    post: operations["submit_report_api_v1_internships__internship_id__reports_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/internships/{internship_id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Démarrer un stage (à partir de sa date de début) */
    post: operations["start_internship_api_v1_internships__internship_id__start_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/internships/{internship_id}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lister les tâches d'un stage (par échéance) */
    get: operations["list_tasks_api_v1_internships__internship_id__tasks_get"];
    put?: never;
    /** Confier une tâche (encadrant du stage ou RH) */
    post: operations["create_task_api_v1_internships__internship_id__tasks_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/reports/{report_id}/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Relire un rapport et laisser un retour (encadrant du stage ou RH) */
    post: operations["review_report_api_v1_reports__report_id__review_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/supervisors": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Lister les encadrants (paginé) */
    get: operations["list_supervisors_api_v1_supervisors_get"];
    put?: never;
    /** Enregistrer un encadrant */
    post: operations["register_supervisor_api_v1_supervisors_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/supervisors/{supervisor_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Consulter un encadrant */
    get: operations["get_supervisor_api_v1_supervisors__supervisor_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{task_id}/complete": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Terminer une tâche */
    post: operations["complete_task_api_v1_tasks__task_id__complete_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/tasks/{task_id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Commencer une tâche */
    post: operations["start_task_api_v1_tasks__task_id__start_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Créer un compte utilisateur (RH) */
    post: operations["create_user_api_v1_users_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sonde de vivacité */
    get: operations["live_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Sonde de disponibilité */
    get: operations["ready_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_login_api_v1_auth_token_post */
    Body_login_api_v1_auth_token_post: {
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
      /** Grant Type */
      grant_type?: string | null;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Username */
      username: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InternCreate */
    InternCreate: {
      /**
       * Email
       * Format: email
       * @example sara.elamrani@example.com
       */
      email: string;
      /**
       * First Name
       * @example Sara
       */
      first_name: string;
      /**
       * Last Name
       * @example El Amrani
       */
      last_name: string;
      /**
       * School
       * @example ENSA Oujda
       */
      school: string;
      /** @example ingenieur */
      study_level: components["schemas"]["StudyLevel"];
    };
    /** InternPage */
    InternPage: {
      /** Items */
      items: components["schemas"]["InternRead"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** InternRead */
    InternRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Email */
      email: string;
      /** First Name */
      first_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Last Name */
      last_name: string;
      /** School */
      school: string;
      study_level: components["schemas"]["StudyLevel"];
    };
    /** InternshipCreate */
    InternshipCreate: {
      /**
       * End Date
       * Format: date
       * @example 2027-03-31
       */
      end_date: string;
      /**
       * Intern Id
       * Format: uuid
       */
      intern_id: string;
      /**
       * Start Date
       * Format: date
       * @example 2026-11-02
       */
      start_date: string;
      /**
       * Subject
       * @example Agent IA de suivi des stagiaires
       */
      subject: string;
      /**
       * Supervisor Id
       * Format: uuid
       */
      supervisor_id: string;
    };
    /** InternshipPage */
    InternshipPage: {
      /** Items */
      items: components["schemas"]["InternshipRead"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** InternshipRead */
    InternshipRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Duration Days
       * @description Durée en jours, bornes incluses.
       */
      duration_days: number;
      /**
       * End Date
       * Format: date
       */
      end_date: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Intern Id
       * Format: uuid
       */
      intern_id: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      status: components["schemas"]["InternshipStatus"];
      /** Subject */
      subject: string;
      /**
       * Supervisor Id
       * Format: uuid
       */
      supervisor_id: string;
    };
    /**
     * InternshipStatus
     * @enum {string}
     */
    InternshipStatus: "planned" | "ongoing" | "completed" | "cancelled";
    /** MeRead */
    MeRead: {
      /** Intern Id */
      intern_id: string | null;
      role: components["schemas"]["Role"];
      /** Supervisor Id */
      supervisor_id: string | null;
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /** ReportCreate */
    ReportCreate: {
      /**
       * Accomplishments
       * @example Mise en place du pipeline d'ingestion.
       */
      accomplishments: string;
      /**
       * Difficulties
       * @default
       */
      difficulties: string;
      /**
       * Next Steps
       * @default
       */
      next_steps: string;
      /**
       * Week
       * @description Semaine ISO 8601, du lundi au dimanche.
       * @example 2026-W41
       */
      week: string;
    };
    /** ReportRead */
    ReportRead: {
      /** Accomplishments */
      accomplishments: string;
      /** Difficulties */
      difficulties: string;
      /** Feedback */
      feedback: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Internship Id
       * Format: uuid
       */
      internship_id: string;
      /** Next Steps */
      next_steps: string;
      /** Reviewed At */
      reviewed_at: string | null;
      status: components["schemas"]["ReportStatus"];
      /**
       * Submitted At
       * Format: date-time
       */
      submitted_at: string;
      /** Week */
      week: string;
      /**
       * Week End
       * Format: date
       */
      week_end: string;
      /**
       * Week Start
       * Format: date
       */
      week_start: string;
    };
    /** ReportReview */
    ReportReview: {
      /**
       * Feedback
       * @example Bon avancement, documenter le schéma.
       */
      feedback: string;
    };
    /**
     * ReportStatus
     * @enum {string}
     */
    ReportStatus: "submitted" | "reviewed";
    /**
     * Role
     * @enum {string}
     */
    Role: "hr" | "supervisor" | "intern";
    /**
     * StudyLevel
     * @description Niveau d'études du stagiaire (système LMD + cycle ingénieur).
     * @enum {string}
     */
    StudyLevel: "bac+2" | "licence" | "master_1" | "master_2" | "ingenieur" | "doctorat";
    /** SupervisorCreate */
    SupervisorCreate: {
      /**
       * Department
       * @example Data & IA
       */
      department: string;
      /**
       * Email
       * Format: email
       * @example karim.benali@example.com
       */
      email: string;
      /**
       * First Name
       * @example Karim
       */
      first_name: string;
      /**
       * Last Name
       * @example Benali
       */
      last_name: string;
      /**
       * Max Interns
       * @description Nombre maximal de stagiaires suivis en même temps.
       * @default 5
       */
      max_interns: number;
    };
    /** SupervisorPage */
    SupervisorPage: {
      /** Items */
      items: components["schemas"]["SupervisorRead"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** SupervisorRead */
    SupervisorRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Department */
      department: string;
      /** Email */
      email: string;
      /** First Name */
      first_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Last Name */
      last_name: string;
      /** Max Interns */
      max_interns: number;
    };
    /** TaskCreate */
    TaskCreate: {
      /**
       * Description
       * @default
       */
      description: string;
      /**
       * Due Date
       * Format: date
       * @example 2026-10-30
       */
      due_date: string;
      /**
       * Title
       * @example Modéliser le schéma de données
       */
      title: string;
    };
    /** TaskRead */
    TaskRead: {
      /** Completed At */
      completed_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      /** Description */
      description: string;
      /**
       * Due Date
       * Format: date
       */
      due_date: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Internship Id
       * Format: uuid
       */
      internship_id: string;
      /**
       * Is Overdue
       * @description Échéance dépassée et tâche non terminée.
       */
      is_overdue: boolean;
      status: components["schemas"]["TaskStatus"];
      /** Title */
      title: string;
    };
    /**
     * TaskStatus
     * @enum {string}
     */
    TaskStatus: "todo" | "in_progress" | "done";
    /**
     * TokenResponse
     * @description Format de réponse OAuth2 (RFC 6749, §5.1).
     */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Expires In
       * @description Durée de validité du jeton, en secondes.
       */
      expires_in: number;
      /**
       * Token Type
       * @default bearer
       * @constant
       */
      token_type: "bearer";
    };
    /** UserCreate */
    UserCreate: {
      /**
       * Email
       * Format: email
       * @example karim.benali@example.com
       */
      email: string;
      /**
       * Intern Id
       * @description Obligatoire pour le rôle intern.
       */
      intern_id?: string | null;
      /**
       * Password
       * Format: password
       * @example une-phrase-de-passe-longue
       */
      password: string;
      role: components["schemas"]["Role"];
      /**
       * Supervisor Id
       * @description Obligatoire pour le rôle supervisor.
       */
      supervisor_id?: string | null;
    };
    /**
     * UserRead
     * @description Le mot de passe et son empreinte ne sortent jamais de l'API.
     */
    UserRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Intern Id */
      intern_id: string | null;
      /** Is Active */
      is_active: boolean;
      role: components["schemas"]["Role"];
      /** Supervisor Id */
      supervisor_id: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MeRead"];
        };
      };
      /** @description Jeton absent ou invalide */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  login_api_v1_auth_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_token_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Identifiants incorrects */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_interns_api_v1_interns_get: {
    parameters: {
      query?: {
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternPage"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  register_intern_api_v1_interns_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InternCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description E-mail déjà utilisé */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Données invalides (RFC 9457) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_intern_api_v1_interns__intern_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        intern_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Stagiaire introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_internships_api_v1_internships_get: {
    parameters: {
      query?: {
        intern_id?: string | null;
        supervisor_id?: string | null;
        status?: components["schemas"]["InternshipStatus"] | null;
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternshipPage"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  plan_internship_api_v1_internships_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InternshipCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternshipRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Stagiaire ou encadrant introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Chevauchement de stages ou capacité de l'encadrant atteinte */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Données invalides (RFC 9457) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_internship_api_v1_internships__internship_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        internship_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternshipRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Stage introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_internship_api_v1_internships__internship_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        internship_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternshipRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Stage introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Transition de statut non autorisée */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  complete_internship_api_v1_internships__internship_id__complete_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        internship_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternshipRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Stage introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Transition de statut non autorisée */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_reports_api_v1_internships__internship_id__reports_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        internship_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportRead"][];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Stage introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_report_api_v1_internships__internship_id__reports_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        internship_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReportCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Stage introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Rapport déjà déposé pour cette semaine, ou stage pas en cours */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_internship_api_v1_internships__internship_id__start_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        internship_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InternshipRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Stage introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Transition de statut non autorisée */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_tasks_api_v1_internships__internship_id__tasks_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        internship_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskRead"][];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Stage introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_task_api_v1_internships__internship_id__tasks_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        internship_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Stage introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Stage terminé ou annulé */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  review_report_api_v1_reports__report_id__review_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        report_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReportReview"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Rapport introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Rapport déjà relu */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_supervisors_api_v1_supervisors_get: {
    parameters: {
      query?: {
        offset?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SupervisorPage"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  register_supervisor_api_v1_supervisors_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupervisorCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SupervisorRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description E-mail déjà utilisé */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Données invalides (RFC 9457) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  get_supervisor_api_v1_supervisors__supervisor_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        supervisor_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SupervisorRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Encadrant introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  complete_task_api_v1_tasks__task_id__complete_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tâche introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Transition refusée ou stage clôturé */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_task_api_v1_tasks__task_id__start_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Action non autorisée pour ce rôle (RFC 9457) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Tâche introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Transition refusée ou stage clôturé */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_user_api_v1_users_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserRead"];
        };
      };
      /** @description Jeton absent, invalide ou expiré (RFC 9457) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Réservé aux RH */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Profil stagiaire / encadrant introuvable */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description E-mail déjà utilisé ou profil déjà lié */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  live_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  ready_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
