"""Création des tables tasks et weekly_reports.

Migration générée par `alembic revision --autogenerate`, puis relue :
l'index sur weekly_reports.internship_id a été retiré (redondant avec la
contrainte UNIQUE (internship_id, iso_year, iso_week)).

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 17:24:07.880622+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('internship_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'done') = (completed_at IS NOT NULL)", name=op.f('ck_tasks_completed_at_matches_status')),
    sa.CheckConstraint("status IN ('todo', 'in_progress', 'done')", name=op.f('ck_tasks_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], name=op.f('fk_tasks_internship_id_internships'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_internship_id'), 'tasks', ['internship_id'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('internship_id', sa.Uuid(), nullable=False),
    sa.Column('iso_year', sa.SmallInteger(), nullable=False),
    sa.Column('iso_week', sa.SmallInteger(), nullable=False),
    sa.Column('accomplishments', sa.Text(), nullable=False),
    sa.Column('difficulties', sa.Text(), nullable=False),
    sa.Column('next_steps', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'reviewed') = (feedback IS NOT NULL AND reviewed_at IS NOT NULL)", name=op.f('ck_weekly_reports_review_matches_status')),
    sa.CheckConstraint("status IN ('submitted', 'reviewed')", name=op.f('ck_weekly_reports_status_valid')),
    sa.CheckConstraint('iso_week BETWEEN 1 AND 53', name=op.f('ck_weekly_reports_iso_week_range')),
    sa.ForeignKeyConstraint(['internship_id'], ['internships.id'], name=op.f('fk_weekly_reports_internship_id_internships'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_reports')),
    sa.UniqueConstraint('internship_id', 'iso_year', 'iso_week', name='uq_weekly_reports_internship_week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_tasks_internship_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
